from rest_framework.exceptions import APIException

class ErrorCode:
    # Generic
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    PARSE_ERROR = "PARSE_ERROR"
    UNSUPPORTED_MEDIA_TYPE = "UNSUPPORTED_MEDIA_TYPE"
    NOT_ACCEPTABLE = "NOT_ACCEPTABLE"
    THROTTLED = "THROTTLED"
    SERVER_ERROR = "SERVER_ERROR"
    INVALID_PAGE = "INVALID_PAGE"

    # Branch
    BRANCH_ACCESS_DENIED = "BRANCH_ACCESS_DENIED"

    # Shipment
    SHIPMENT_INVALID_STATUS = "SHIPMENT_INVALID_STATUS"
    SHIPMENT_INVALID_TRANSITION = "SHIPMENT_INVALID_TRANSITION"

    # Collection
    COLLECTION_TASK_INVALID_STATUS = "COLLECTION_TASK_INVALID_STATUS"
    COLLECTION_TASK_ACCESS_DENIED = "COLLECTION_TASK_ACCESS_DENIED"
    COLLECTION_COLLECTOR_INACTIVE = "COLLECTION_COLLECTOR_INACTIVE"
    COLLECTION_COLLECTOR_ROLE_REQUIRED = "COLLECTION_COLLECTOR_ROLE_REQUIRED"
    COLLECTION_COLLECTOR_BRANCH_MISMATCH = "COLLECTION_COLLECTOR_BRANCH_MISMATCH"
    COLLECTION_PARCEL_WRONG_TASK = "COLLECTION_PARCEL_WRONG_TASK"
    COLLECTION_WEIGHT_INVALID = "COLLECTION_WEIGHT_INVALID"
    COLLECTION_LENGTH_INVALID = "COLLECTION_LENGTH_INVALID"
    COLLECTION_WIDTH_INVALID = "COLLECTION_WIDTH_INVALID"
    COLLECTION_HEIGHT_INVALID = "COLLECTION_HEIGHT_INVALID"
    COLLECTION_PARCELS_UNVERIFIED = "COLLECTION_PARCELS_UNVERIFIED"
    COLLECTION_PARCEL_REQUIRED = "COLLECTION_PARCEL_REQUIRED"

    # Invoice
    INVOICE_ALREADY_EXISTS = "INVOICE_ALREADY_EXISTS"
    INVOICE_NUMBER_EXISTS = "INVOICE_NUMBER_EXISTS"
    INVOICE_INVALID_STATUS = "INVOICE_INVALID_STATUS"
    INVOICE_PARCEL_REQUIRED = "INVOICE_PARCEL_REQUIRED"
    INVOICE_PARCEL_NOT_BELONG = "INVOICE_PARCEL_NOT_BELONG"
    INVOICE_PARCEL_DUPLICATE = "INVOICE_PARCEL_DUPLICATE"
    INVOICE_CHARGE_AMOUNT_INVALID = "INVOICE_CHARGE_AMOUNT_INVALID"
    INVOICE_PAYER_INVALID = "INVOICE_PAYER_INVALID"
    INVOICE_ACCESS_DENIED = "INVOICE_ACCESS_DENIED"
    INVOICE_USER_INACTIVE = "INVOICE_USER_INACTIVE"

    # Dispatch
    DISPATCH_BATCH_EMPTY = "DISPATCH_BATCH_EMPTY"
    DISPATCH_BATCH_INVALID_STATUS = "DISPATCH_BATCH_INVALID_STATUS"
    DISPATCH_ORDER_INVALID_STATUS = "DISPATCH_ORDER_INVALID_STATUS"
    DISPATCH_ORDER_ALREADY_IN_BATCH = "DISPATCH_ORDER_ALREADY_IN_BATCH"
    DISPATCH_ORDER_NOT_READY = "DISPATCH_ORDER_NOT_READY"
    DISPATCH_ORDER_BRANCH_MISMATCH = "DISPATCH_ORDER_BRANCH_MISMATCH"
    DISPATCH_FREIGHT_ASSIGNMENT_REQUIRED = (
        "DISPATCH_FREIGHT_ASSIGNMENT_REQUIRED"
    )
    DISPATCH_FREIGHT_ASSIGNMENT_INVALID_STATUS = (
        "DISPATCH_FREIGHT_ASSIGNMENT_INVALID_STATUS"
    )
    DISPATCH_PAYER_INVALID = "DISPATCH_PAYER_INVALID"
    DISPATCH_FREIGHT_INVOICE_REQUIRED = (
        "DISPATCH_FREIGHT_INVOICE_REQUIRED"
    )
    DISPATCH_DISPATCHER_INACTIVE = "DISPATCH_DISPATCHER_INACTIVE"
    DISPATCH_DISPATCHER_BRANCH_MISMATCH = (
        "DISPATCH_DISPATCHER_BRANCH_MISMATCH"
    )
    DISPATCH_DISPATCHER_REQUIRED = "DISPATCH_DISPATCHER_REQUIRED"
    DISPATCH_ONLY_ASSIGNED_DISPATCHER = (
        "DISPATCH_ONLY_ASSIGNED_DISPATCHER"
    )
    DISPATCH_REJECTION_REASON_REQUIRED = (
        "DISPATCH_REJECTION_REASON_REQUIRED"
    )
    DISPATCH_ACTIVE_ASSIGNMENT_EXISTS = (
        "DISPATCH_ACTIVE_ASSIGNMENT_EXISTS"
    )

class BusinessRuleError(APIException):
    status_code = 400
    default_code = ErrorCode.VALIDATION_ERROR
    default_detail = "The requested operation is not allowed."

    def __init__(self, detail=None, code=None):
        self.default_code = code or self.default_code
        super().__init__(detail=detail)

class BusinessPermissionError(APIException):
    status_code = 403
    default_code = ErrorCode.PERMISSION_DENIED
    default_detail = "You do not have permission to perform this action."

    def __init__(self, detail=None, code=None):
        self.default_code = code or self.default_code
        super().__init__(detail=detail)