# Generated by Django 3.2.25 on 2026-08-14 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tracking_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('barcode', models.CharField(editable=False, max_length=50, unique=True)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_mobile', models.CharField(max_length=20)),
                ('sender_address', models.TextField()),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_mobile', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('declared_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_length_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_height_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contents_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('operator_review', 'Operator Review'), ('approved_for_collection', 'Approved for Collection'), ('collected', 'Collected'), ('received_at_branch', 'Received at Branch'), ('invoice_registered', 'Invoice Registered'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched_to_freight', 'Dispatched to Freight'), ('handover_pending_approval', 'Handover Pending Approval'), ('handover_approved', 'Handover Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='submitted', max_length=40)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='freight.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='freight.customer')),
                ('preferred_freight_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_orders', to='freight.freightcompany')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
