# Generated by Django 3.2.25 on 2026-08-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0002_shipmentorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentorder',
            name='declared_height_cm',
        ),
        migrations.RemoveField(
            model_name='shipmentorder',
            name='declared_length_cm',
        ),
        migrations.RemoveField(
            model_name='shipmentorder',
            name='declared_weight_kg',
        ),
        migrations.RemoveField(
            model_name='shipmentorder',
            name='declared_width_cm',
        ),
        migrations.CreateModel(
            name='ShipmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=40, null=True)),
                ('to_status', models.CharField(max_length=40)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipment_status_changes', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='freight.shipmentorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.PositiveIntegerField()),
                ('declared_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_length_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_width_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('declared_height_cm', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contents_description', models.TextField(blank=True)),
                ('verified_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verified_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verified_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verified_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('difference_found', 'Difference Found')], default='pending', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='freight.shipmentorder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['parcel_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='parcel',
            constraint=models.UniqueConstraint(fields=('order', 'parcel_number'), name='unique_parcel_number_per_order'),
        ),
    ]
