# Generated by Django 3.2.25 on 2026-08-15 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0003_auto_20260815_1451'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentorder',
            old_name='contents_description',
            new_name='shipment_description',
        ),
    ]
