# Generated by Django 3.2.25 on 2026-08-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0005_collectiontask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectiontask',
            options={'permissions': [('assign_collection_task', 'Can assign collection task'), ('start_collection_task', 'Can start collection task'), ('verify_collection_task', 'Can verify collection task'), ('complete_collection_task', 'Can complete collection task'), ('cancel_collection_task', 'Can cancel collection task')]},
        ),
    ]
