# Generated by Django 3.2.25 on 2026-09-01 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0006_alter_collectiontask_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_mobile', models.CharField(max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_mobile', models.CharField(max_length=20)),
                ('receiver_address', models.TextField()),
                ('payment_payer', models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=20)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='freight.shipmentorder')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_type', models.CharField(choices=[('freight', 'Freight'), ('insurance', 'Insurance'), ('crane_loading', 'Crane / Loading'), ('branch', 'Branch'), ('other', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='freight.invoice')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
