# Generated by Django 3.2.25 on 2026-09-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0007_invoice_invoicecharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.PositiveIntegerField()),
                ('parcel_name', models.CharField(blank=True, max_length=255)),
                ('parcel_type', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='freight.invoice')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='freight.parcel')),
            ],
            options={
                'ordering': ['parcel_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoiceparcel',
            constraint=models.UniqueConstraint(fields=('invoice', 'parcel'), name='unique_invoice_parcel'),
        ),
    ]
