# Generated by Django 3.2.25 on 2026-09-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0008_auto_20260901_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_payer',
        ),
        migrations.AddField(
            model_name='invoicecharge',
            name='payer',
            field=models.CharField(blank=True, choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=20, null=True),
        ),
    ]
