# Generated by Django 3.2.25 on 2026-09-06 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freight', '0009_auto_20260901_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready for Dispatch'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_batches', to='freight.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_dispatch_batches', to=settings.AUTH_USER_MODEL)),
                ('dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='freight.dispatchbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='freight.shipmentorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DispatchFreightAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='selected', max_length=30)),
                ('payer', models.CharField(choices=[('sender', 'Sender'), ('receiver', 'Receiver')], max_length=20)),
                ('freight_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('freight_invoice_number', models.CharField(blank=True, max_length=100)),
                ('freight_invoice_file', models.FileField(blank=True, null=True, upload_to='freight_invoices/')),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_freight_assignments', to=settings.AUTH_USER_MODEL)),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight_assignments', to='freight.dispatchorder')),
                ('freight_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_assignments', to='freight.freightcompany')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
