# Generated by Django 3.2.25 on 2026-09-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0010_dispatchbatch_dispatchfreightassignment_dispatchorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispatchbatch',
            options={'ordering': ['-created_at'], 'permissions': [('assign_dispatcher', 'Can assign dispatcher'), ('add_order_to_dispatch', 'Can add order to dispatch'), ('remove_order_from_dispatch', 'Can remove order from dispatch'), ('start_dispatch', 'Can start dispatch'), ('complete_dispatch', 'Can complete dispatch')]},
        ),
    ]
