# Generated by Django 3.2.25 on 2026-09-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0011_alter_dispatchbatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchbatch',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
