# Generated by Django 3.2.25 on 2026-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0012_dispatchbatch_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchfreightassignment',
            old_name='accepted_at',
            new_name='approved_at',
        ),
        migrations.RemoveField(
            model_name='dispatchbatch',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='dispatchbatch',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='dispatchfreightassignment',
            name='delivered_at',
        ),
        migrations.AlterField(
            model_name='dispatchbatch',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispatchfreightassignment',
            name='status',
            field=models.CharField(choices=[('dispatching', 'Dispatching'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='dispatching', max_length=30),
        ),
        migrations.AlterField(
            model_name='dispatchorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
    ]
