# Generated by Django 3.2.25 on 2026-09-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freight', '0013_auto_20260911_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('operator_review', 'Operator Review'), ('approved_for_collection', 'Approved for Collection'), ('collected', 'Collected'), ('received_at_branch', 'Received at Branch'), ('invoice_registered', 'Invoice Registered'), ('ready_for_dispatch', 'Ready for Dispatch'), ('dispatched_to_freight', 'Dispatched to Freight'), ('handover_pending_approval', 'Handover Pending Approval'), ('handover_approved', 'Handover Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='draft', max_length=40),
        ),
        migrations.AlterField(
            model_name='shipmentorder',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
